create table BATCH.BATCH
(
    ID               NUMBER       not null
        constraint PK_BATCH
            primary key,
    CODE             VARCHAR2(50) not null,
    APIINVENTORYCODE VARCHAR2(50) not null,
    CREATEDATE       DATE,
    CREATEUSER       VARCHAR2(50),
    UPDATEUSER       VARCHAR2(50),
    UPDATEDATE       DATE,
    VERSIONID        NUMBER,
    COMPANYID        NUMBER,
    constraint UK_BATCH_CODE_COMPANYID
        unique (CODE, COMPANYID)
)
/




create sequence BATCH.BATCH_S
    /


INSERT INTO BATCH.BATCH (ID, CODE, APIINVENTORYCODE, PROCESSGROUPID, CREATEDATE, CREATEUSER, UPDATEUSER, UPDATEDATE, VERSIONID, COMPANYID)
VALUES (1, 'OUTDATEDPAYMENT', 'BTCH', TIMESTAMP '2024-11-06 21:12:19', 'test', 'test', TIMESTAMP '2024-11-06 21:12:19', 0, 1);

INSERT INTO BATCH.BATCH (ID, CODE, APIINVENTORYCODE, PROCESSGROUPID, CREATEDATE, CREATEUSER, UPDATEUSER, UPDATEDATE, VERSIONID, COMPANYID)
VALUES (2, 'OUTDATEDPAYMENT', 'BTCH', TIMESTAMP '2024-12-01 10:52:15', 'test', 'test', TIMESTAMP '2024-12-01 10:52:15', 0, 2);


